export interface SMEPlan {
  id: string;
  name: string;
  company: string;
  type: string;
  annualLimit: string;
  annualLimitValue: number;
  lifeInsurance: string;
  tpa: string;
  network: string;
  accommodation: string;
  inpatient: string;
  consultations: string;
  radiologyLab: string;
  medications: string;
  dental: string;
  optical: string;
  maternity: string;
  chronicPreExisting: string;
  covid19: string;
  outOfNetwork: string;
  minMembers: number;
  maxMembers: number;
  paymentTerms: string;
  basePremium?: number; 
}

export const SME_PLANS: SMEPlan[] = [
  {
    "id": "Sarwa General -001",
    "company": "Sarwa General",
    "name": "Platinum",
    "type": "Platinum",
    "lifeInsurance": "Not covered",
    "annualLimit": "150,000 EGP",
    "annualLimitValue": 150000,
    "tpa": "GlobeMed",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "\"1,000 EGP",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "waiting period 10 Months\"",
    "company": "15000 EGP",
    "name": "Full coverage",
    "type": "Full coverage",
    "lifeInsurance": "80% Cleopatra Hospital, doctor visits up to 300 EGP",
    "annualLimit": "10",
    "annualLimitValue": 10,
    "tpa": "150",
    "network": "Below 100K annual, Below 200K semiannual, above 200K quarterly",
    "accommodation": "",
    "inpatient": "",
    "consultations": "",
    "radiologyLab": "",
    "medications": "",
    "dental": "",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "Sarwa General -002",
    "company": "Sarwa General",
    "name": "Titanium",
    "type": "Titanium",
    "lifeInsurance": "Not covered",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "GlobeMed",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "\"1,000 EGP",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "waiting period 10 Months\"",
    "company": "10,000 EGP",
    "name": "Full coverage",
    "type": "Full coverage",
    "lifeInsurance": "80% Cleopatra Hospital, doctor visits up to 300 EGP",
    "annualLimit": "10",
    "annualLimitValue": 10,
    "tpa": "150",
    "network": "Below 100K annual, Below 200K semiannual, above 200K quarterly",
    "accommodation": "",
    "inpatient": "",
    "consultations": "",
    "radiologyLab": "",
    "medications": "",
    "dental": "",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "Sarwa General -003",
    "company": "Sarwa General",
    "name": "Golden",
    "type": "Golden",
    "lifeInsurance": "Not covered",
    "annualLimit": "50,000 EGP",
    "annualLimitValue": 50000,
    "tpa": "GlobeMed",
    "network": "Limited Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "90% coverage",
    "radiologyLab": "90% coverage",
    "medications": "80% coverage",
    "dental": "\"500 EGP",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "waiting period 10 Months\"",
    "company": "5,000 EGP",
    "name": "Full coverage",
    "type": "Full coverage",
    "lifeInsurance": "80% Misr international Hospital, doctor visits up to 300 EGP",
    "annualLimit": "10",
    "annualLimitValue": 10,
    "tpa": "150",
    "network": "Below 100K annual, Below 200K semiannual, above 200K quarterly",
    "accommodation": "",
    "inpatient": "",
    "consultations": "",
    "radiologyLab": "",
    "medications": "",
    "dental": "",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "Sarwa General -004",
    "company": "Sarwa General",
    "name": "Silver",
    "type": "Silver",
    "lifeInsurance": "Not covered",
    "annualLimit": "30,000 EGP",
    "annualLimitValue": 30000,
    "tpa": "GlobeMed",
    "network": "Limited Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "Not covered",
    "optical": "Not covered",
    "maternity": "Not covered",
    "chronicPreExisting": "2,500 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Doctor Syndicate, doctor visits up to 300 EGP",
    "minMembers": 10,
    "maxMembers": 150,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "AXA-001",
    "company": "AXA",
    "name": "Prestige  Advanced Plus",
    "type": "Prestige  Advanced Plus",
    "lifeInsurance": "200,000 EGP",
    "annualLimit": "250,000 EGP",
    "annualLimitValue": 250000,
    "tpa": "AXA Egypt",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "2,500 EGP (20% copayment)",
    "optical": "1,500 EGP (2 cases per every 20 insured)",
    "maternity": "7,500 EGP (2 cases per every 20 insured)",
    "chronicPreExisting": "25,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Coverage on reimbursement basis",
    "minMembers": 20,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "AXA-002",
    "company": "AXA",
    "name": "Prestige  Plus",
    "type": "Prestige  Plus",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "150,000 EGP",
    "annualLimitValue": 150000,
    "tpa": "AXA Egypt",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "1,500 EGP  (20% copayment)",
    "optical": "1,000 EGP (2 cases per every 20 insured)",
    "maternity": "7,500 EGP (2 cases per every 20 insured)",
    "chronicPreExisting": "15,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Coverage on reimbursement basis",
    "minMembers": 20,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "AXA-003",
    "company": "AXA",
    "name": "Elite Plus",
    "type": "Elite Plus",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "AXA Egypt",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "1,000 EGP (20% copayment)",
    "optical": "600 EGP (2 cases per every 20 insured)",
    "maternity": "5,000 EGP (2 cases per every 20 insured)",
    "chronicPreExisting": "10,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Coverage on reimbursement basis",
    "minMembers": 20,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "AXA-004",
    "company": "AXA",
    "name": "Elite",
    "type": "Elite",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "50,000 EGP",
    "annualLimitValue": 50000,
    "tpa": "AXA Egypt",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "500 EGP (20% copayment)",
    "optical": "400 EGP (2 cases per every 20 insured)",
    "maternity": "3,000 EGP (1 cases per every 20 insured)",
    "chronicPreExisting": "5,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Coverage on reimbursement basis",
    "minMembers": 20,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Arop-001",
    "company": "Arop",
    "name": "Premier",
    "type": "Premier",
    "lifeInsurance": "Not covered",
    "annualLimit": "300,000 EGP",
    "annualLimitValue": 300000,
    "tpa": "GlobeMed",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "2,000 EGP (10% copayment)",
    "optical": "\"2,000 EGP",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "(10% copayment)\"",
    "company": "15,000 EGP",
    "name": "35,000 EGP",
    "type": "35,000 EGP",
    "lifeInsurance": "Full coverage",
    "annualLimit": "80% Cleopatra Hospital",
    "annualLimitValue": 80,
    "tpa": "10",
    "network": "150",
    "accommodation": "Below 100K annual, Below 200K semiannual, above 200K quarterly",
    "inpatient": "",
    "consultations": "",
    "radiologyLab": "",
    "medications": "",
    "dental": "",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "Arop-002",
    "company": "Arop",
    "name": "Platinum",
    "type": "Platinum",
    "lifeInsurance": "Not covered",
    "annualLimit": "200,000 EGP",
    "annualLimitValue": 200000,
    "tpa": "GlobeMed",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "\"1,500 EGP",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "(10% copayment)\"",
    "company": "10,000 EGP",
    "name": "25,000 EGP",
    "type": "25,000 EGP",
    "lifeInsurance": "Full coverage",
    "annualLimit": "80% Cleopatra Hospital",
    "annualLimitValue": 80,
    "tpa": "10",
    "network": "150",
    "accommodation": "Below 100K annual, Below 200K semiannual, above 200K quarterly",
    "inpatient": "",
    "consultations": "",
    "radiologyLab": "",
    "medications": "",
    "dental": "",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "Arop-003",
    "company": "Arop",
    "name": "Silver",
    "type": "Silver",
    "lifeInsurance": "Not covered",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "GlobeMed",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "\"1,000 EGP",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "(10% copayment)\"",
    "company": "5,000 EGP",
    "name": "10,000 EGP",
    "type": "10,000 EGP",
    "lifeInsurance": "Full coverage",
    "annualLimit": "80% Misr international Hospital",
    "annualLimitValue": 80,
    "tpa": "10",
    "network": "150",
    "accommodation": "Below 100K annual, Below 200K semiannual, above 200K quarterly",
    "inpatient": "",
    "consultations": "",
    "radiologyLab": "",
    "medications": "",
    "dental": "",
    "optical": "",
    "maternity": "",
    "chronicPreExisting": "",
    "covid19": "",
    "outOfNetwork": "",
    "minMembers": 0,
    "maxMembers": 0,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-001",
    "company": "Libnano suisse",
    "name": "Platunium Tier 4",
    "type": "Platunium Tier 4",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "GlobeMed",
    "network": "Tier 4",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "800 EGP",
    "optical": "1000 EGP",
    "maternity": "5,000 EGP",
    "chronicPreExisting": "20,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Cleopatra Hospital, doctor visits up to 250 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-002",
    "company": "Libnano suisse",
    "name": "Platunium Tier 3",
    "type": "Platunium Tier 3",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "GlobeMed",
    "network": "Tier 3",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "800 EGP",
    "optical": "1000 EGP",
    "maternity": "5,000 EGP",
    "chronicPreExisting": "20,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Cleopatra Hospital, doctor visits up to 250 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-003",
    "company": "Libnano suisse",
    "name": "Ultimate Tier 4",
    "type": "Ultimate Tier 4",
    "lifeInsurance": "150,000 EGP",
    "annualLimit": "150,000 EGP",
    "annualLimitValue": 150000,
    "tpa": "GlobeMed",
    "network": "Tier 4",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "500 EGP (10% of Memebers)",
    "optical": "500 EGP (10% of Memebers)",
    "maternity": "7,000 EGP",
    "chronicPreExisting": "25,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Cleopatra Hospital, doctor visits up to 150 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-004",
    "company": "Libnano suisse",
    "name": "Ultimate Tier 3",
    "type": "Ultimate Tier 3",
    "lifeInsurance": "150,000 EGP",
    "annualLimit": "150,000 EGP",
    "annualLimitValue": 150000,
    "tpa": "GlobeMed",
    "network": "Tier 3",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "500 EGP (10% of Memebers)",
    "optical": "500 EGP (10% of Memebers)",
    "maternity": "7,000 EGP",
    "chronicPreExisting": "25,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Cleopatra Hospital, doctor visits up to 150 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-005",
    "company": "Libnano suisse",
    "name": "Superio Tier 4",
    "type": "Superio Tier 4",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "GlobeMed",
    "network": "Tier 4",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "75% coverage",
    "dental": "500 EGP (10% of Memebers)",
    "optical": "500 EGP (10% of Memebers)",
    "maternity": "3,000 EGP",
    "chronicPreExisting": "20,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "70% Cleopatra Hospital, doctor visits up to 150 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-006",
    "company": "Libnano suisse",
    "name": "Superio Tier 3",
    "type": "Superio Tier 3",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "GlobeMed",
    "network": "Tier 3",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "75% coverage",
    "dental": "500 EGP (10% of Memebers)",
    "optical": "500 EGP (10% of Memebers)",
    "maternity": "3,000 EGP",
    "chronicPreExisting": "20,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "70% Cleopatra Hospital, doctor visits up to 150 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-007",
    "company": "Libnano suisse",
    "name": "Premium Tier 4",
    "type": "Premium Tier 4",
    "lifeInsurance": "60,000 EGP",
    "annualLimit": "60,000 EGP",
    "annualLimitValue": 60000,
    "tpa": "GlobeMed",
    "network": "Tier 4",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "90% Coverage",
    "radiologyLab": "90% Coverage",
    "medications": "80% coverage",
    "dental": "500 EGP",
    "optical": "400 EGP",
    "maternity": "3,000 EGP",
    "chronicPreExisting": "7,500 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Cleopatra Hospital, doctor visits up to 250 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-008",
    "company": "Libnano suisse",
    "name": "Premium Tier 3",
    "type": "Premium Tier 3",
    "lifeInsurance": "60,000 EGP",
    "annualLimit": "60,000 EGP",
    "annualLimitValue": 60000,
    "tpa": "GlobeMed",
    "network": "Tier 3",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "90% Coverage",
    "radiologyLab": "90% Coverage",
    "medications": "80% coverage",
    "dental": "500 EGP",
    "optical": "400 EGP",
    "maternity": "3,000 EGP",
    "chronicPreExisting": "7,500 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Cleopatra Hospital, doctor visits up to 250 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-009",
    "company": "Libnano suisse",
    "name": "Protect Tier 4",
    "type": "Protect Tier 4",
    "lifeInsurance": "50,000 EGP",
    "annualLimit": "50,000 EGP",
    "annualLimitValue": 50000,
    "tpa": "GlobeMed",
    "network": "Tier 4",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "75% Coverage",
    "radiologyLab": "75% Coverage",
    "medications": "75% Coverage",
    "dental": "500 EGP (10% of Memebers)",
    "optical": "500 EGP (10% of Memebers)",
    "maternity": "2,000 EGP",
    "chronicPreExisting": "5,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "70% Cleopatra Hospital, doctor visits up to 100 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-010",
    "company": "Libnano suisse",
    "name": "Protect Tier 3",
    "type": "Protect Tier 3",
    "lifeInsurance": "50,000 EGP",
    "annualLimit": "50,000 EGP",
    "annualLimitValue": 50000,
    "tpa": "GlobeMed",
    "network": "Tier 3",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "75% Coverage",
    "radiologyLab": "75% Coverage",
    "medications": "75% Coverage",
    "dental": "500 EGP (10% of Memebers)",
    "optical": "500 EGP (10% of Memebers)",
    "maternity": "2,000 EGP",
    "chronicPreExisting": "5,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "70% Cleopatra Hospital, doctor visits up to 100 EGP",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-011",
    "company": "Libnano suisse",
    "name": "Primary Tier 4",
    "type": "Primary Tier 4",
    "lifeInsurance": "25,000 EGP",
    "annualLimit": "25,000 EGP",
    "annualLimitValue": 25000,
    "tpa": "GlobeMed",
    "network": "Tier 4",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "75% Coverage",
    "radiologyLab": "75% Coverage",
    "medications": "75% Coverage",
    "dental": "300 EGP (10% of Memebers)",
    "optical": "300 EGP (10% of Memebers)",
    "maternity": "Not Covered",
    "chronicPreExisting": "2,500 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "Not Covered",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Libnano suisse-012",
    "company": "Libnano suisse",
    "name": "Primary Tier 3",
    "type": "Primary Tier 3",
    "lifeInsurance": "25,000 EGP",
    "annualLimit": "25,000 EGP",
    "annualLimitValue": 25000,
    "tpa": "GlobeMed",
    "network": "Tier 3",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "75% Coverage",
    "radiologyLab": "75% Coverage",
    "medications": "75% Coverage",
    "dental": "300 EGP (10% of Memebers)",
    "optical": "300 EGP (10% of Memebers)",
    "maternity": "Not Covered",
    "chronicPreExisting": "2,500 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "Not Covered",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Metlife-001",
    "company": "Metlife",
    "name": "Diamond",
    "type": "Diamond",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "Metlife",
    "network": "Full network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "800 EGP (20% copayment)",
    "optical": "600 EGP (10% of population)",
    "maternity": "5,000 EGP (10% of population)",
    "chronicPreExisting": "10,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "",
    "minMembers": 51,
    "maxMembers": 300,
    "paymentTerms": ""
  },
  {
    "id": "Metlife-002",
    "company": "Metlife",
    "name": "Golden",
    "type": "Golden",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "50,000 EGP",
    "annualLimitValue": 50000,
    "tpa": "Metlife",
    "network": "Full network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "90% coverage",
    "radiologyLab": "90% coverage",
    "medications": "80% coverage",
    "dental": "500 EGP (20% copayment)",
    "optical": "400 EGP 10% of population",
    "maternity": "3,000 EGP (10% of population)",
    "chronicPreExisting": "5,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "",
    "minMembers": 21,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Metlife-003",
    "company": "Metlife",
    "name": "Silver (A)",
    "type": "Silver (A)",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "25,000 EGP",
    "annualLimitValue": 25000,
    "tpa": "Metlife",
    "network": "Full network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "350 EGP (20% copayment)",
    "optical": "Not covered",
    "maternity": "Not covered",
    "chronicPreExisting": "3,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "",
    "minMembers": 21,
    "maxMembers": 100,
    "paymentTerms": ""
  },
  {
    "id": "Metlife-004",
    "company": "Metlife",
    "name": "Silver (B)",
    "type": "Silver (B)",
    "lifeInsurance": "25,000 EGP",
    "annualLimit": "15,000 EGP",
    "annualLimitValue": 15000,
    "tpa": "Metlife",
    "network": "Limited Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "70% coverage",
    "radiologyLab": "70% coverage",
    "medications": "70% coverage",
    "dental": "Not covered",
    "optical": "Not covered",
    "maternity": "Not covered",
    "chronicPreExisting": "Not covered",
    "covid19": "Full coverage",
    "outOfNetwork": "",
    "minMembers": 21,
    "maxMembers": 100,
    "paymentTerms": ""
  },
  {
    "id": "Misr Insurance Takaful-001",
    "company": "Misr Insurance Takaful",
    "name": "Diamond",
    "type": "Diamond",
    "lifeInsurance": "Not covered",
    "annualLimit": "200,000 EGP",
    "annualLimitValue": 200000,
    "tpa": "NextCare",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "1,000 EGP",
    "optical": "800 EGP",
    "maternity": "7,500 EGP",
    "chronicPreExisting": "20,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% according to applicable costs",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Misr Insurance Takaful-002",
    "company": "Misr Insurance Takaful",
    "name": "Platinum",
    "type": "Platinum",
    "lifeInsurance": "Not covered",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "NextCare",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "90% coverage",
    "medications": "80% coverage",
    "dental": "800 EGP",
    "optical": "600 EGP",
    "maternity": "5,000 EGP",
    "chronicPreExisting": "10,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% according to applicable costs",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Misr Insurance Takaful-003",
    "company": "Misr Insurance Takaful",
    "name": "Gold",
    "type": "Gold",
    "lifeInsurance": "Not covered",
    "annualLimit": "75,000 EGP",
    "annualLimitValue": 75000,
    "tpa": "NextCare",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "700 EGP",
    "optical": "400 EGP",
    "maternity": "4,000 EGP",
    "chronicPreExisting": "7,500 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% according to applicable costs",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Misr Insurance Takaful-004",
    "company": "Misr Insurance Takaful",
    "name": "Silver",
    "type": "Silver",
    "lifeInsurance": "Not covered",
    "annualLimit": "30,000 EGP",
    "annualLimitValue": 30000,
    "tpa": "NextCare",
    "network": "Limited Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "500 EGP",
    "optical": "200 EGP",
    "maternity": "3,000 EGP",
    "chronicPreExisting": "5,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% according to applicable costs",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Misr Insurance Takaful-005",
    "company": "Misr Insurance Takaful",
    "name": "Bronze",
    "type": "Bronze",
    "lifeInsurance": "Not covered",
    "annualLimit": "30,000 EGP",
    "annualLimitValue": 30000,
    "tpa": "NextCare",
    "network": "Restricted Network",
    "accommodation": "Double room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "70% coverage",
    "medications": "70% coverage",
    "dental": "300 EGP",
    "optical": "Not Covered",
    "maternity": "Not Covered",
    "chronicPreExisting": "3,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "Not Covered",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Sarwa Life-001",
    "company": "Sarwa Life",
    "name": "Plan 1",
    "type": "Plan 1",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "GlobeMed",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "1,000 EGP (20% copayment)",
    "optical": "700 EGP (20% copayment)",
    "maternity": "7,000 EGP",
    "chronicPreExisting": "10,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Misr international Hospital, doctor visits up to 300 EGP",
    "minMembers": 5,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Sarwa Life-002",
    "company": "Sarwa Life",
    "name": "Plan 2",
    "type": "Plan 2",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "50,000 EGP",
    "annualLimitValue": 50000,
    "tpa": "GlobeMed",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "90% coverage",
    "radiologyLab": "90% coverage",
    "medications": "80% coverage",
    "dental": "500 EGP (20% copayment)",
    "optical": "500 EGP (20% copayment)",
    "maternity": "3,000 EGP",
    "chronicPreExisting": "5,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Misr international Hospital, doctor visits up to 300 EGP",
    "minMembers": 5,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Sarwa Life-003",
    "company": "Sarwa Life",
    "name": "Plan 3",
    "type": "Plan 3",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "30,000 EGP",
    "annualLimitValue": 30000,
    "tpa": "GlobeMed",
    "network": "Restricted Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "Not Covered",
    "optical": "Not Covered",
    "maternity": "Not Covered",
    "chronicPreExisting": "2,500 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Misr international Hospital, doctor visits up to 300 EGP",
    "minMembers": 5,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Sarwa Life-004",
    "company": "Sarwa Life",
    "name": "Plan 4",
    "type": "Plan 4",
    "lifeInsurance": "50,000 EGP",
    "annualLimit": "50,000 EGP",
    "annualLimitValue": 50000,
    "tpa": "GlobeMed",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "Not Covered",
    "radiologyLab": "Not Covered",
    "medications": "Not Covered",
    "dental": "Not Covered",
    "optical": "Not Covered",
    "maternity": "Not Covered",
    "chronicPreExisting": "Not Covered",
    "covid19": "Not Covered",
    "outOfNetwork": "Not Covered",
    "minMembers": 5,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Sarwa Life-005",
    "company": "Sarwa Life",
    "name": "Plan 5",
    "type": "Plan 5",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "150,000 EGP",
    "annualLimitValue": 150000,
    "tpa": "GlobeMed",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "100% coverage",
    "radiologyLab": "100% coverage",
    "medications": "80% coverage",
    "dental": "1,500 EGP (20% copayment)",
    "optical": "1,000 EGP (20% copayment)",
    "maternity": "7,000 EGP",
    "chronicPreExisting": "15,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "80% Misr international Hospital, doctor visits up to 300 EGP",
    "minMembers": 5,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Sarwa Life-006",
    "company": "Sarwa Life",
    "name": "Plan 6",
    "type": "Plan 6",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "GlobeMed",
    "network": "Limited Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "Not Covered",
    "optical": "Not Covered",
    "maternity": "Not Covered",
    "chronicPreExisting": "7,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "75% Misr international Hospital, doctor visits up to 300 EGP",
    "minMembers": 5,
    "maxMembers": 250,
    "paymentTerms": "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    "id": "Sarwa Life-007",
    "company": "",
    "name": "Plan 7",
    "type": "Plan 7",
    "lifeInsurance": "100,000 EGP",
    "annualLimit": "50,000 EGP",
    "annualLimitValue": 50000,
    "tpa": "GlobeMed",
    "network": "Limited Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "Not Covered",
    "optical": "Not Covered",
    "maternity": "Not Covered",
    "chronicPreExisting": "2,500 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "75% Misr international Hospital, doctor visits up to 300 EGP",
    "minMembers": 5,
    "maxMembers": 250,
    "paymentTerms": ""
  },
  {
    "id": "Orient-001",
    "company": "Orient",
    "name": "Plan A",
    "type": "Plan A",
    "lifeInsurance": "Not covered",
    "annualLimit": "250,000 EGP",
    "annualLimitValue": 250000,
    "tpa": "NextCare",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "90% coverage",
    "radiologyLab": "90% coverage",
    "medications": "80% coverage",
    "dental": "2,500 EGP (20% copayment)",
    "optical": "2,000 EGP (20% copayment)",
    "maternity": "20,000 EGP",
    "chronicPreExisting": "25,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Orient-002",
    "company": "Orient",
    "name": "Plan B",
    "type": "Plan B",
    "lifeInsurance": "Not covered",
    "annualLimit": "150,000 EGP",
    "annualLimitValue": 150000,
    "tpa": "NextCare",
    "network": "Full Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "1,500 EGP (20% copayment)",
    "optical": "1,000 EGP (20% copayment)",
    "maternity": "15,000 EGP",
    "chronicPreExisting": "15,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Orient-003",
    "company": "Orient",
    "name": "Plan C",
    "type": "Plan C",
    "lifeInsurance": "Not covered",
    "annualLimit": "150,000 EGP",
    "annualLimitValue": 150000,
    "tpa": "NextCare",
    "network": "Limited Network",
    "accommodation": "Single room",
    "inpatient": "Full coverage",
    "consultations": "90% coverage",
    "radiologyLab": "90% coverage",
    "medications": "80% coverage",
    "dental": "1,000 EGP (20% copayment)",
    "optical": "1,000 EGP (20% copayment)",
    "maternity": "10,000 EGP",
    "chronicPreExisting": "15,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  },
  {
    "id": "Orient-004",
    "company": "Orient",
    "name": "Plan D",
    "type": "Plan D",
    "lifeInsurance": "Not covered",
    "annualLimit": "100,000 EGP",
    "annualLimitValue": 100000,
    "tpa": "NextCare",
    "network": "Limited Network",
    "accommodation": "Double room",
    "inpatient": "Full coverage",
    "consultations": "80% coverage",
    "radiologyLab": "80% coverage",
    "medications": "80% coverage",
    "dental": "500 EGP (20% copayment)",
    "optical": "500 EGP (20% copayment)",
    "maternity": "7,500 EGP",
    "chronicPreExisting": "10,000 EGP",
    "covid19": "Full coverage",
    "outOfNetwork": "",
    "minMembers": 20,
    "maxMembers": 200,
    "paymentTerms": ""
  }
];
