
export interface SMEPlan {
  id: string;
  name: string;
  company: string;
  type: string;
  annualLimit: string;
  annualLimitValue: number;
  lifeInsurance: string;
  tpa: string;
  network: string;
  accommodation: string;
  inpatient: string;
  consultations: string;
  radiologyLab: string;
  medications: string;
  dental: string;
  optical: string;
  maternity: string;
  chronicPreExisting: string;
  covid19: string;
  outOfNetwork: string;
  minMembers: number;
  maxMembers: number;
  paymentTerms: string;
  basePremium?: number; 
}

export const SME_PLANS: SMEPlan[] = [
  // --- SARWA GENERAL ---
  {
    id: "Sarwa General -001",
    name: "Platinum",
    company: "Sarwa General",
    type: "Platinum",
    annualLimit: "150,000 EGP",
    annualLimitValue: 150000,
    lifeInsurance: "Not covered",
    tpa: "GlobeMed",
    network: "Full Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "100% coverage",
    radiologyLab: "100% coverage",
    medications: "80% coverage",
    dental: "1,000 EGP (20% copayment)",
    optical: "700 EGP (20% copayment)",
    maternity: "7000 EGP waiting period 10 Months",
    chronicPreExisting: "15,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "80% Cleopatra Hospital, doctor visits up to 300 EGP",
    minMembers: 10,
    maxMembers: 150,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Sarwa General -002",
    name: "Titanium",
    company: "Sarwa General",
    type: "Titanium",
    annualLimit: "100,000 EGP",
    annualLimitValue: 100000,
    lifeInsurance: "Not covered",
    tpa: "GlobeMed",
    network: "Full Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "100% coverage",
    radiologyLab: "100% coverage",
    medications: "80% coverage",
    dental: "1,000 EGP (20% copayment)",
    optical: "700 EGP (20% copayment)",
    maternity: "7000 EGP waiting period 10 Months",
    chronicPreExisting: "10,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "80% Cleopatra Hospital, doctor visits up to 300 EGP",
    minMembers: 10,
    maxMembers: 150,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Sarwa General -003",
    name: "Golden",
    company: "Sarwa General",
    type: "Golden",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "GlobeMed",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "90% coverage",
    radiologyLab: "90% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "500 EGP (20% copayment)",
    maternity: "3000 EGP waiting period 10 Months",
    chronicPreExisting: "5,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "80% Misr international Hospital, doctor visits up to 300 EGP",
    minMembers: 10,
    maxMembers: 150,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Sarwa General -004",
    name: "Silver",
    company: "Sarwa General",
    type: "Silver",
    annualLimit: "30,000 EGP",
    annualLimitValue: 30000,
    lifeInsurance: "Not covered",
    tpa: "GlobeMed",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "Not covered",
    optical: "Not covered",
    maternity: "Not covered",
    chronicPreExisting: "2,500 EGP",
    covid19: "Full coverage",
    outOfNetwork: "80% Doctor Syndicate, doctor visits up to 300 EGP",
    minMembers: 10,
    maxMembers: 150,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },

  // --- AXA ---
  {
    id: "AXA-001",
    name: "Prestige Plus",
    company: "AXA",
    type: "Prestige Plus",
    annualLimit: "150,000 EGP",
    annualLimitValue: 150000,
    lifeInsurance: "100,000 EGP",
    tpa: "Axa Egypt",
    network: "Full Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "100% coverage",
    radiologyLab: "100% coverage",
    medications: "80% coverage",
    dental: "1500 EGP (20% copayment)",
    optical: "1000 EGP (20% copayment) 2 cases per every 20 insured",
    maternity: "7500 EGP 2 cases per every 20 insured",
    chronicPreExisting: "15,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "AXA-002",
    name: "Elite Plus",
    company: "AXA",
    type: "Elite Plus",
    annualLimit: "100,000 EGP",
    annualLimitValue: 100000,
    lifeInsurance: "100,000 EGP",
    tpa: "Axa Egypt",
    network: "Full Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "100% coverage",
    radiologyLab: "100% coverage",
    medications: "80% coverage",
    dental: "1000 EGP (20% copayment)",
    optical: "600 EGP (20% copayment) 2 cases per every 20 insured",
    maternity: "5000 EGP 2 cases per every 20 insured",
    chronicPreExisting: "10,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "AXA-003",
    name: "Diamond Plus",
    company: "AXA",
    type: "Diamond Plus",
    annualLimit: "100,000 EGP",
    annualLimitValue: 100000,
    lifeInsurance: "100,000 EGP",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "1000 EGP (20% copayment)",
    optical: "600 EGP (20% copayment) 2 cases per every 20 insured",
    maternity: "5000 EGP (2 cases per every 20 insured)",
    chronicPreExisting: "10,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "AXA-004",
    name: "Elite",
    company: "AXA",
    type: "Elite",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "100,000 EGP",
    tpa: "Axa Egypt",
    network: "Full Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "AXA-005",
    name: "Diamond",
    company: "AXA",
    type: "Diamond",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "100,000 EGP",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },

  // --- AROP ---
  {
    id: "Arop-001",
    name: "Premier",
    company: "Arop",
    type: "Premier",
    annualLimit: "300,000 EGP",
    annualLimitValue: 300000,
    lifeInsurance: "Not covered",
    tpa: "GlobeMed",
    network: "Full Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "100% coverage",
    radiologyLab: "100% coverage",
    medications: "80% coverage",
    dental: "2,000 EGP (10% copayment)",
    optical: "2,000 EGP (10% copayment)",
    maternity: "15,000 EGP",
    chronicPreExisting: "35,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Standard",
    minMembers: 10,
    maxMembers: 150,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Arop-002",
    name: "Platinum",
    company: "Arop",
    type: "Platinum",
    annualLimit: "200,000 EGP",
    annualLimitValue: 200000,
    lifeInsurance: "Not covered",
    tpa: "GlobeMed",
    network: "Full Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "100% coverage",
    radiologyLab: "100% coverage",
    medications: "80% coverage",
    dental: "1,500 EGP (10% copayment)",
    optical: "1,500 EGP (10% copayment)",
    maternity: "10,000 EGP",
    chronicPreExisting: "25,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Standard",
    minMembers: 10,
    maxMembers: 150,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Arop-003",
    name: "Silver",
    company: "Arop",
    type: "Silver",
    annualLimit: "100,000 EGP",
    annualLimitValue: 100000,
    lifeInsurance: "Not covered",
    tpa: "GlobeMed",
    network: "Full Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "1,000 EGP (10% copayment)",
    optical: "1,000 EGP (10% copayment)",
    maternity: "5,000 EGP",
    chronicPreExisting: "10,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Standard",
    minMembers: 10,
    maxMembers: 150,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },

  // --- CHUBB ---
  {
    id: "Chubb-001",
    name: "Radiant",
    company: "Chubb",
    type: "Radiant",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Limited",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Chubb-002",
    name: "Vibrant",
    company: "Chubb",
    type: "Vibrant",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Limited",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Chubb-003",
    name: "Confident",
    company: "Chubb",
    type: "Confident",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Limited",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Chubb-004",
    name: "Peaceful",
    company: "Chubb",
    type: "Peaceful",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Limited",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },

  // --- GIG ---
  {
    id: "GIG-001",
    name: "VIP",
    company: "GIG",
    type: "VIP",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "None",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "GIG-002",
    name: "Platinum",
    company: "GIG",
    type: "Platinum",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "None",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "GIG-003",
    name: "Platinum Lite",
    company: "GIG",
    type: "Platinum Lite",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "None",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "GIG-004",
    name: "Gold",
    company: "GIG",
    type: "Gold",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "None",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "GIG-005",
    name: "Gold Lite",
    company: "GIG",
    type: "Gold Lite",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "None",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "GIG-006",
    name: "Gold Lite Plus",
    company: "GIG",
    type: "Gold Lite Plus",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "None",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "GIG-007",
    name: "Silver",
    company: "GIG",
    type: "Silver",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "None",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },

  // --- LABANO-SUISSE ---
  {
    id: "Labno swiss-001",
    name: "Plan1",
    company: "Labano-suisse",
    type: "Labno swiss Plan1",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Labno swiss-002",
    name: "Plan2",
    company: "Labano-suisse",
    type: "Labno swiss Plan2",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Labno swiss-003",
    name: "Plan3",
    company: "Labano-suisse",
    type: "Labno swiss Plan3",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Labno swiss-004",
    name: "Plan4",
    company: "Labano-suisse",
    type: "Labno swiss Plan4",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Labno swiss-005",
    name: "Plan5",
    company: "Labano-suisse",
    type: "Labno swiss Plan5",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Labno swiss-006",
    name: "Plan6",
    company: "Labano-suisse",
    type: "Labno swiss Plan6",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },

  // --- METLIFE ---
  {
    id: "Metlife-001",
    name: "Diamond",
    company: "Metlife",
    type: "Diamond",
    annualLimit: "100,000 EGP",
    annualLimitValue: 100000,
    lifeInsurance: "100,000 EGP",
    tpa: "Metlife",
    network: "Full network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "100% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "800 EGP (20% copayment)",
    optical: "600 EGP (10% of population)",
    maternity: "5,000 EGP (10% of population)",
    chronicPreExisting: "10,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 51,
    maxMembers: 300,
    paymentTerms: "Standard"
  },
  {
    id: "Metlife-002",
    name: "Golden",
    company: "Metlife",
    type: "Golden",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "100,000 EGP",
    tpa: "Metlife",
    network: "Full network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "90% coverage",
    radiologyLab: "90% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP 10% of population",
    maternity: "3,000 EGP (10% of population)",
    chronicPreExisting: "5,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 21,
    maxMembers: 200,
    paymentTerms: "Standard"
  },
  {
    id: "Metlife-003",
    name: "Silver (A)",
    company: "Metlife",
    type: "Silver (A)",
    annualLimit: "25,000 EGP",
    annualLimitValue: 25000,
    lifeInsurance: "100,000 EGP",
    tpa: "Metlife",
    network: "Full network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "350 EGP (20% copayment)",
    optical: "Not covered",
    maternity: "Not covered",
    chronicPreExisting: "3,000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 21,
    maxMembers: 100,
    paymentTerms: "Standard"
  },
  {
    id: "Metlife-004",
    name: "Silver (B)",
    company: "Metlife",
    type: "Silver (B)",
    annualLimit: "15,000 EGP",
    annualLimitValue: 15000,
    lifeInsurance: "25,000 EGP",
    tpa: "Metlife",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "70% coverage",
    radiologyLab: "70% coverage",
    medications: "70% coverage",
    dental: "Not covered",
    optical: "Not covered",
    maternity: "Not covered",
    chronicPreExisting: "Not covered",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 21,
    maxMembers: 100,
    paymentTerms: "Standard"
  },

  // --- MISR INSURANCE TAKAFUL ---
  {
    id: "Misr Insurance Takaful-001",
    name: "Option 1",
    company: "Misr Insurance Takaful",
    type: "Misr Insurance Takaful Option 1",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Misr Insurance Takaful-002",
    name: "Option 2",
    company: "Misr Insurance Takaful",
    type: "Misr Insurance Takaful Option 2",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Misr Insurance Takaful-003",
    name: "Option 3",
    company: "Misr Insurance Takaful",
    type: "Misr Insurance Takaful Option 3",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Misr Insurance Takaful-004",
    name: "Option 4",
    company: "Misr Insurance Takaful",
    type: "Misr Insurance Takaful Option 4",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Misr Insurance Takaful-005",
    name: "Option 5",
    company: "Misr Insurance Takaful",
    type: "Misr Insurance Takaful Option 5",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },

  // --- SARWA LIFE ---
  {
    id: "Sarwa Life-001",
    name: "Option 1",
    company: "Sarwa Life",
    type: "Sarwa Life Option 1",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Sarwa Life-002",
    name: "Option 2",
    company: "Sarwa Life",
    type: "Sarwa Life Option 2",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Sarwa Life-003",
    name: "Option 3",
    company: "Sarwa Life",
    type: "Sarwa Life Option 3",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Sarwa Life-004",
    name: "Option 4",
    company: "Sarwa Life",
    type: "Sarwa Life Option 4",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Sarwa Life-005",
    name: "Option 5",
    company: "Sarwa Life",
    type: "Sarwa Life Option 5",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Sarwa Life-006",
    name: "Option 6",
    company: "Sarwa Life",
    type: "Sarwa Life Option 6",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },

  // --- KAF ---
  {
    id: "Kaf-001",
    name: "Option 1",
    company: "Kaf",
    type: "KAF Option 1",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Kaf-002",
    name: "Option 2",
    company: "Kaf",
    type: "KAF Option 2",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Kaf-003",
    name: "Option 3",
    company: "Kaf",
    type: "KAF Option 3",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Kaf-004",
    name: "Option 4",
    company: "Kaf",
    type: "KAF Option 4",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  },
  {
    id: "Kaf-005",
    name: "Option 5",
    company: "Kaf",
    type: "KAF Option 5",
    annualLimit: "50,000 EGP",
    annualLimitValue: 50000,
    lifeInsurance: "Not covered",
    tpa: "Axa Egypt",
    network: "Limited Network",
    accommodation: "Single room",
    inpatient: "Full coverage",
    consultations: "80% coverage",
    radiologyLab: "80% coverage",
    medications: "80% coverage",
    dental: "500 EGP (20% copayment)",
    optical: "400 EGP (20% copayment) 1 cases per every 20 insured",
    maternity: "3000 EGP (1 cases per every 20 insured)",
    chronicPreExisting: "5000 EGP",
    covid19: "Full coverage",
    outOfNetwork: "Reimbursement",
    minMembers: 20,
    maxMembers: 250,
    paymentTerms: "Below 100K annual, Below 200K semiannual, above 200K quarterly"
  }
];
