export const TEMPLATE_HEADERS = [
  "Insurer Name",
  "Policy Name",
  "Policy Number",
  "TPA Name",
  "Policy Start Date",
  "Policy End Date",
  "Member Code",
  "Plan Name",
  "Service Date",
  "Provider Name",
  "Provider Type (Hospital / Clinic / Pharmacy / Lab / Radiology)",
  "Medical Network (In-Network / Out-of-Network)",
  "Diagnosis Description",
  "ICD Code",
  "Chronic Condition (Yes/No)",
  "Pre-existing Condition (Yes/No)",
  "Case Type (Inpatient / Outpatient / Emergency / Maternity / Dental / Optical)",
  "Approval Amount",
  "Co-payment",
  "Net Amount",
  "Approval Number",
  "Approval Status (Approved / Rejected / Pending)",
  "Length of Stay (Days)",
  "Admission Type (Elective / Emergency)"
];
