import sys
import json
import os
import io
import matplotlib.pyplot as plt
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.graphics.shapes import Drawing, Rect, String, Circle
from reportlab.graphics import renderPDF

# Configure basic styles
styles = getSampleStyleSheet()
primary_color = colors.HexColor("#4f46e5")
secondary_color = colors.HexColor("#334155")
accent_color = colors.HexColor("#f1f5f9")
text_muted = colors.HexColor("#64748b")

# Define Custom Styles
title_style = ParagraphStyle(
    'CustomTitle',
    parent=styles['Heading1'],
    fontSize=28,
    textColor=primary_color,
    alignment=1,
    spaceAfter=10,
    fontName='Helvetica-Bold'
)

h2_style = ParagraphStyle(
    'SectionHeader',
    parent=styles['Heading2'],
    fontSize=18,
    textColor=primary_color,
    borderLeftColor=primary_color,
    borderLeftWidth=3,
    leftIndent=10,
    spaceBefore=20,
    spaceAfter=15,
    fontName='Helvetica-Bold'
)

bubble_left_style = ParagraphStyle(
    'BubbleLeft',
    parent=styles['Normal'],
    fontSize=10,
    textColor=secondary_color,
    backgroundColor=accent_color,
    borderPadding=10,
    borderRadius=12,
    leading=14,
    fontName='Helvetica'
)

bubble_right_style = ParagraphStyle(
    'BubbleRight',
    parent=styles['Normal'],
    fontSize=10,
    textColor=colors.white,
    backgroundColor=primary_color,
    borderPadding=10,
    borderRadius=12,
    leading=14,
    alignment=2,
    fontName='Helvetica'
)

def create_pricing_chart(plans, snapshots):
    plt.style.use('ggplot')
    names = [p['name'] for p in plans]
    premiums = [snapshots.get(p['id'], {}).get('premium', 0) for p in plans]
    
    fig, ax = plt.subplots(figsize=(6, 3.5))
    bars = ax.bar(names, premiums, color='#4f46e5', alpha=0.8)
    
    # Add labels on top of bars
    for bar in bars:
        height = bar.get_height()
        ax.text(bar.get_x() + bar.get_width()/2., height + 5,
                f'{int(height):,}', ha='center', va='bottom', fontsize=9)

    ax.set_title('Annual Premium Comparison (EGP)', fontsize=12, pad=15, color='#1e293b')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)
    plt.xticks(rotation=0)
    plt.tight_layout()
    
    img_data = io.BytesIO()
    plt.savefig(img_data, format='png', dpi=150, transparent=True)
    plt.close()
    img_data.seek(0)
    return img_data

def create_benefit_chart(plans):
    # Dynamic benefit score based on annual limit value
    plt.figure(figsize=(6, 3.5))
    names = [p['name'] for p in plans]
    # Use annualLimitValue if available, otherwise mock it
    scores = [p.get('annualLimitValue', 0) / 1000 for p in plans]
    
    plt.barh(names, scores, color='#10b981', alpha=0.7)
    plt.title('Plan Coverage Capacity (k EGP)', fontsize=12, pad=15)
    plt.tight_layout()
    
    img_data = io.BytesIO()
    plt.savefig(img_data, format='png', dpi=150, transparent=True)
    plt.close()
    img_data.seek(0)
    return img_data

def draw_logo(canvas, x, y):
    # Draw a stylized logo box
    canvas.saveState()
    canvas.setFillColor(primary_color)
    canvas.roundRect(x, y, 120, 60, 8, fill=1, stroke=0)
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica-Bold", 24)
    canvas.drawString(x + 15, y + 25, "IWIB")
    canvas.setFont("Helvetica-Bold", 8)
    canvas.drawString(x + 15, y + 12, "BROKERAGE")
    canvas.restoreState()

def add_header_footer(canvas, doc):
    canvas.saveState()
    # Footer
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(text_muted)
    footer_text = "Generated by IWIB System | Confidential Proposal | www.iwib-eg.com"
    canvas.drawCentredString(A4[0]/2, 30, footer_text)
    canvas.drawRightString(A4[0] - 40, 30, f"Page {doc.page}")
    canvas.restoreState()

class ChatMessage(Table):
    def __init__(self, text, side='left', author="Expert"):
        p = Paragraph(f"<b>{author}:</b><br/>{text}", 
                    bubble_left_style if side == 'left' else bubble_right_style)
        
        # Add a placeholder for icon
        icon_color = primary_color if side == 'left' else colors.HexColor("#10b981")
        
        data = [[p]]
        col_widths = [4.5*inch]
        super().__init__(data, colWidths=col_widths)
        self.hAlign = 'LEFT' if side == 'left' else 'RIGHT'
        self.setStyle(TableStyle([
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('LEFTPADDING', (0,0), (-1,-1), 12),
            ('RIGHTPADDING', (0,0), (-1,-1), 12),
        ]))

def generate_pdf(input_data, output_path):
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=60
    )
    
    story = []
    
    # --- 1. COVER PAGE ---
    story.append(Spacer(1, 1.5*inch))
    # Logo will be drawn via canvas but we can add space here
    story.append(Spacer(1, 1*inch))
    
    story.append(Paragraph(input_data.get('offerName', 'INSURANCE PROPOSAL'), title_style))
    story.append(Spacer(1, 0.5*inch))
    
    # Client Info Box
    client_info = [
        [Paragraph(f"<font color='#64748b'>PREPARED FOR</font><br/><br/><font size='16' color='#1e293b'><b>{input_data.get('companyName', 'Valued Client')}</b></font>", styles['Normal'])]
    ]
    cit = Table(client_info, colWidths=[5*inch])
    cit.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), accent_color),
        ('LEFTPADDING', (0,0), (-1,-1), 20),
        ('RIGHTPADDING', (0,0), (-1,-1), 20),
        ('TOPPADDING', (0,0), (-1,-1), 20),
        ('BOTTOMPADDING', (0,0), (-1,-1), 20),
    ]))
    story.append(cit)
    
    story.append(Spacer(1, 0.5*inch))
    story.append(Paragraph(f"<b>Issue Date:</b> {input_data.get('date', 'N/A')}", styles['Normal']))
    story.append(Paragraph(f"<b>Reference:</b> {input_data.get('id', 'IWIB-PRP-001')}", styles['Normal']))
    
    story.append(Spacer(1, 2*inch))
    
    # Contact Info
    contact_text = """
    <b>IWIB CONTACT DETAILS</b><br/>
    Address: 5 Alnakheel St., Mohandessin<br/>
    Hotline: 01013330409 | Email: info@iwib-eg.com<br/>
    Website: www.iwib-eg.com
    """
    story.append(Paragraph(contact_text, ParagraphStyle('Contact', parent=styles['Normal'], fontSize=9, textColor=text_muted, leading=12)))
    
    story.append(PageBreak())
    
    # --- 2. EXECUTIVE SUMMARY & GRAPHS ---
    story.append(Paragraph("Market Comparison Overview", h2_style))
    story.append(Paragraph("A comprehensive look at how selected plans compare in terms of cost and capacity.", styles['Normal']))
    story.append(Spacer(1, 0.2*inch))
    
    # Pricing Graph
    pricing_img = create_pricing_chart(input_data['plans'], input_data['snapshots'])
    story.append(KeepTogether([
        Paragraph("<b>Premium Distribution</b>", styles['Normal']),
        Spacer(1, 0.1*inch),
        Image(pricing_img, width=5.5*inch, height=3*inch)
    ]))
    
    story.append(Spacer(1, 0.4*inch))
    
    # Benefit Graph
    benefit_img = create_benefit_chart(input_data['plans'])
    story.append(KeepTogether([
        Paragraph("<b>Plan Capacity Score</b>", styles['Normal']),
        Spacer(1, 0.1*inch),
        Image(benefit_img, width=5.5*inch, height=3*inch)
    ]))
    
    story.append(PageBreak())
    
    # --- 3. CONVERSATIONAL ANALYSIS (CHAT STYLE) ---
    story.append(Paragraph("Expert Plan Analysis", h2_style))
    story.append(Paragraph("Our experts break down why these plans were shortlisted for you.", styles['Normal']))
    story.append(Spacer(1, 0.3*inch))
    
    # Default chat if not provided
    chat_msgs = input_data.get('chat', [
        {"side": "left", "author": "IWIB Advisor", "text": "Based on your company profile, we've selected these three TPAs for their strong network in Mohandessin."},
        {"side": "right", "author": "System", "text": "Analyzing Plan A vs Plan B... Plan A offers better maternity coverage."},
        {"side": "left", "author": "Advisor", "text": "Correct. However, Plan B has a wider network of specialized clinics which might be better for your employees' demographics."}
    ])
    
    for msg in chat_msgs:
        story.append(ChatMessage(msg['text'], msg['side'], msg.get('author', 'Advisor')))
        story.append(Spacer(1, 0.15*inch))
        
    story.append(Spacer(1, 0.5*inch))
    
    # --- 4. DETAILED BENEFITS TABLE ---
    story.append(Paragraph("Side-by-Side Comparison", h2_style))
    
    # Prepare Table Data
    headers = [Paragraph("<b>Benefit</b>", styles['Normal'])]
    for p in input_data['plans']:
        headers.append(Paragraph(f"<b>{p['company']}<br/><font size='8' color='#4f46e5'>{p['name']}</font></b>", styles['Normal']))
    
    table_data = [headers]
    
    key_benefits = [
        ('annualLimit', 'Annual Limit'),
        ('tpa', 'TPA'),
        ('network', 'Network'),
        ('inpatient', 'Inpatient'),
        ('medications', 'Medications'),
        ('dental', 'Dental'),
        ('optical', 'Optical')
    ]
    
    for key, label in key_benefits:
        row = [Paragraph(f"<b>{label}</b>", styles['Normal'])]
        for p in input_data['plans']:
            val = p.get(key, 'N/A')
            row.append(Paragraph(str(val), styles['Normal']))
        table_data.append(row)
        
    t = Table(table_data, repeatRows=1, colWidths=[1.2*inch] + [(4.5/len(input_data['plans']))*inch]*len(input_data['plans']))
    t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), accent_color),
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t)
    
    # Build the PDF
    def my_first_page(canvas, doc):
        add_header_footer(canvas, doc)
        draw_logo(canvas, 40, A4[1] - 100)
        
    def my_later_pages(canvas, doc):
        add_header_footer(canvas, doc)
        
    doc.build(story, onFirstPage=my_first_page, onLaterPages=my_later_pages)

if __name__ == "__main__":
    if len(sys.argv) < 3:
        # For testing, generate a sample
        sample_data = {
            "offerName": "SME Medical Insurance Proposal",
            "companyName": "TechCorp Solutions",
            "date": "May 7, 2026",
            "plans": [
                {"id": "p1", "name": "Platinum", "company": "MetLife", "annualLimit": "500,000 EGP", "annualLimitValue": 500000, "tpa": "NextCare", "network": "Diamond", "inpatient": "100%", "medications": "80%", "dental": "2000 EGP", "optical": "1500 EGP"},
                {"id": "p2", "name": "Gold Plus", "company": "AXA", "annualLimit": "300,000 EGP", "annualLimitValue": 300000, "tpa": "Globemed", "network": "L0", "inpatient": "100%", "medications": "70%", "dental": "1500 EGP", "optical": "1000 EGP"}
            ],
            "snapshots": {
                "p1": {"premium": 45000},
                "p2": {"premium": 32000}
            }
        }
        generate_pdf(sample_data, "test_output.pdf")
    else:
        with open(sys.argv[1], 'r') as f:
            data = json.load(f)
        generate_pdf(data, sys.argv[2])
